#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade HG on Sat Jul  9 18:10:43 2011

import wx

# begin wxGlade: extracode
# end wxGlade



class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1, style=wx.SIMPLE_BORDER)
        self.label_1 = wx.StaticText(self.panel_1, -1, "Bootstrapping main gui\n\n")
        self.bg_type = wx.RadioBox(self.panel_1, -1, "Type", choices=["Vehicles simulation", "Landroids", "Logged data"], majorDimension=0, style=wx.RA_SPECIFY_ROWS)
        self.bg_save_bag = wx.CheckBox(self.panel_1, -1, "Save bag file")
        self.bg_output_dir = wx.TextCtrl(self.panel_1, -1, "")
        self.bg_button_run = wx.Button(self.panel_1, -1, "Create .launch")
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        self.label_4 = wx.StaticText(self.notebook_1_pane_1, -1, "Vehicle\n", style=wx.ALIGN_RIGHT)
        self.bg_vehicle_list = wx.ComboBox(self.notebook_1_pane_1, -1, choices=[], style=wx.CB_DROPDOWN|wx.CB_SIMPLE|wx.CB_DROPDOWN|wx.CB_READONLY)
        self.bg_vehicle_desc = wx.StaticText(self.notebook_1_pane_1, -1, "")
        self.label_2 = wx.StaticText(self.notebook_1_pane_1, -1, "World\n", style=wx.ALIGN_RIGHT)
        self.bg_world_list = wx.ComboBox(self.notebook_1_pane_1, -1, choices=[], style=wx.CB_DROPDOWN|wx.CB_SIMPLE|wx.CB_DROPDOWN|wx.CB_READONLY)
        self.bg_world_desc = wx.StaticText(self.notebook_1_pane_1, -1, "")
        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_3 = wx.Panel(self.notebook_1, -1)
        self.panel_agent = wx.Panel(self, -1)
        self.label_3 = wx.StaticText(self.panel_agent, -1, "Agent")
        self.bg_agent_list = wx.ComboBox(self.panel_agent, -1, choices=["Not initialized"], style=wx.CB_DROPDOWN|wx.CB_SIMPLE|wx.CB_DROPDOWN|wx.CB_READONLY)
        self.bg_agent_desc = wx.StaticText(self.panel_agent, -1, "")
        self.panel_tasks = wx.Panel(self, -1)
        self.label_5 = wx.StaticText(self.panel_tasks, -1, "Tasks")
        self.bg_task_list = wx.ComboBox(self.panel_tasks, -1, choices=[], style=wx.CB_DROPDOWN|wx.CB_SIMPLE|wx.CB_DROPDOWN|wx.CB_READONLY)
        self.bg_task_desc = wx.StaticText(self.panel_tasks, -1, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.h_button_run, self.bg_button_run)
        self.Bind(wx.EVT_COMBOBOX, self.h_vehicle_selected, self.bg_vehicle_list)
        self.Bind(wx.EVT_COMBOBOX, self.h_world_selected, self.bg_world_list)
        self.Bind(wx.EVT_COMBOBOX, self.h_agent_selected, self.bg_agent_list)
        self.Bind(wx.EVT_COMBOBOX, self.h_task_selected, self.bg_task_list)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Bootstrapping GUI")
        self.bg_type.Enable(False)
        self.bg_type.SetSelection(0)
        self.bg_save_bag.Enable(False)
        self.bg_agent_list.SetSelection(0)
        self.bg_task_list.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.FlexGridSizer(2, 2, 10, 10)
        grid_sizer_3 = wx.FlexGridSizer(3, 2, 10, 10)
        grid_sizer_2 = wx.FlexGridSizer(3, 2, 10, 10)
        grid_sizer_1 = wx.FlexGridSizer(4, 2, 10, 10)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(self.label_1, 0, 0, 0)
        sizer_2.Add(self.bg_type, 0, 0, 0)
        sizer_2.Add(self.bg_save_bag, 0, 0, 0)
        sizer_2.Add(self.bg_output_dir, 0, wx.EXPAND, 0)
        sizer_2.Add(self.bg_button_run, 0, 0, 0)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 2, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_4, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.bg_vehicle_list, 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.bg_vehicle_desc, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.bg_world_list, 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.bg_world_desc, 0, wx.EXPAND, 0)
        self.notebook_1_pane_1.SetSizer(grid_sizer_1)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Vehicles")
        self.notebook_1.AddPage(self.notebook_1_pane_2, "Landroids")
        self.notebook_1.AddPage(self.notebook_1_pane_3, "Logged")
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_3, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.bg_agent_list, 0, 0, 0)
        grid_sizer_2.Add(self.bg_agent_desc, 0, 0, 0)
        self.panel_agent.SetSizer(grid_sizer_2)
        sizer_1.Add(self.panel_agent, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(self.label_5, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_3.Add(self.bg_task_list, 0, 0, 0)
        grid_sizer_3.Add(self.bg_task_desc, 0, 0, 0)
        self.panel_tasks.SetSizer(grid_sizer_3)
        sizer_1.Add(self.panel_tasks, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def h_vehicle_selected(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `h_vehicle_selected' not implemented"
        event.Skip()

    def h_world_selected(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `h_world_selected' not implemented"
        event.Skip()

    def h_agent_selected(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `h_agent_selected' not implemented"
        event.Skip()

    def h_task_selected(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `h_task_selected' not implemented"
        event.Skip()

    def h_button_run(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `h_button_run' not implemented"
        event.Skip()

# end of class MyFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
